default: &default
  database: cache
  store_options:
    max_age: <%= 1.year.to_i %>
    max_size: <%= 1.gigabyte %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
