# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gemspec path: "../../"

gem "accept_language",                          "~> 2.0"
gem "active_storage_validations",               "~> 3.0"
gem "addressable",                              "~> 2.8"
gem "amazing_print",                            "~> 2.0", require: false
gem "bcrypt",                                   "~> 3.1"
gem "bootstrap",                                "~> 5.3"
gem "cloudinary",                               "~> 2.4"
gem "commonmarker",                             "~> 2.8"
gem "dartsass-rails",                           "~> 0.5"
gem "dotenv-rails",                             "~> 3.2"
gem "email_validator",                          "~> 2.2"
gem "friendly_id",                              "~> 5.5"
gem "haml-rails",                               "~> 2.1"
gem "http",                                     "~> 5.0", require: false
gem "image_processing",                         "~> 1.14"
gem "importmap-rails",                          "~> 2.0"
gem "lexxy",                                    "~> 0.1"
gem "listen",                                   "~> 3.9"
gem "memo_wise",                                "~> 1.9"
gem "mission_control-jobs",                     "~> 1.0"
gem "paper_trail",                              "~> 16.0"
gem "propshaft",                                "~> 1.0"
gem "pry-rails",                                "~> 0.3"
gem "puma",                                     "~> 7.0", require: false
gem "rack-cors",                                "~> 3.0"
gem "rails-i18n",                               "~> 8.0"
gem "rails",                                    "~> 8.0.1"
gem "ransack",                                  "~> 4.0"
gem "readline",                                 "~> 0.0" # Necessary for Pry if Ruby was not compiled with Readline support.
gem "reverse_markdown",                         "~> 3.0"
gem "sentry-rails",                             "~> 5.8"
gem "solid_cable",                              "~> 3.0"
gem "solid_cache",                              "~> 1.0"
gem "solid_queue",                              "~> 1.0"
gem "sqlite3",                                  "~> 2.5"
gem "stimulus-rails",                           "~> 1.3"
gem "tailwindcss-rails",                        "~> 4.4"
gem "turbo-rails",                              "~> 2.0"
gem "view_component",                           "~> 4.0"
gem "zstd-ruby",                                "~> 1.5"

group :development do
  gem "annotaterb",                             "~> 4.21", require: false
  gem "better_errors",                          github: "manuelmeurer/better_errors", branch: "translation-error-locale-link"
  gem "binding_of_caller",                      "~> 2.0"
  gem "rubocop-rails-omakase",                  "~> 1.1", require: false
  gem "rubocop",                                "~> 1.75", require: false
end
