name: CI

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Enable debugging with tmate
        type: boolean
        required: false
        default: false
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/spec/dummy/Gemfile
      RAILS_ENV: test
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}

      - name: Run tests
        run: |
          set -o pipefail
          echo '```' >> $GITHUB_STEP_SUMMARY
          bundle exec parallel_rspec spec | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: ":collision: *Baseline CI failed*"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":collision: *Baseline CI failed*\n:point_right: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Show run>"

      - name: Upload screenshots
        uses: actions/upload-artifact@v7
        with:
          name: screenshots
          path: tmp/capybara
        if: failure()
